# Generated by Django 3.1.2 on 2020-10-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_discounted_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='to_product',
            new_name='top_product',
        ),
    ]
