# Generated by Django 3.1.2 on 2020-10-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201024_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.UUIDField(),
        ),
    ]
