# Generated by Django 3.1.2 on 2020-10-24 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201024_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
