# Generated by Django 3.1.2 on 2020-10-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201024_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='01787201430', max_length=20),
            preserve_default=False,
        ),
    ]
