# Generated by Django 3.1.2 on 2020-10-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
