# Generated by Django 3.1.2 on 2020-10-24 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201024_1501'),
        ('shop', '0013_auto_20201024_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.addressandinfo'),
        ),
    ]
