# Generated by Django 3.1.2 on 2020-10-24 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201024_1501'),
        ('shop', '0015_auto_20201025_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile'),
        ),
    ]
