# Generated by Django 3.0.5 on 2020-10-22 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(default='', unique=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(default='', unique=True)),
                ('price', models.FloatField(default=10.0)),
                ('featured', models.BinaryField(default=False)),
                ('top_product', models.BinaryField(default=False)),
                ('reward_point', models.FloatField(default=0.0)),
                ('cash_back_percent', models.FloatField(default=0.0)),
                ('category', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
                ('sub_category', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory', unique=True)),
            ],
        ),
    ]
